### ISSUE TITLE
License

### ISSUE THREAD

**Issue by alexprice1** [FaridSafi/react-native-basketball#3]
Very cool! Any way you could add a license to this? MIT works great :)

**Comment by danielksan81** [comment]
Hi, I can add the MIT Licence to the repo and add a note to the readme if wanted.

**Comment by alexprice1** [comment]
Yeah that would be awesome!

**Comment by danielksan81** [comment]
PR #4 created

**Comment by FaridSafi** [comment]
Thank you guys
